### ISSUE TITLE
Where is my API key?

### ISSUE THREAD

**Issue by kush1960** [gathercontent/api-examples#1]
Hi I'm assuming that your API examples use the latest version of your API (not the legacy version I can see in my account).

Only problem is when I click the button to generate my API key, give it a description... Then I don't get an API key! I've followed the instructions here... https://gathercontent.com/developers/authentication/

![screen shot 2016-01-15 at 16 33 45](https://cloud.githubusercontent.com/assets/1533576/12358570/cca7783e-bba5-11e5-8dd3-edadd5aab62b.png)

If I try and use your API example script with the Legacy API I get a 401 error.

**Comment by acairns** [comment]
This is a known issue and a fix will be shipped in a few days which contains a rebuild of this panel.

There is a work-around: logging out and back in! It sounds crazy, but it fixes the flash data issue and the API key gets displayed again.

If this doesn't resolve your issue, let me know and I'll create one for you manually

**Comment by kush1960** [comment]
Thanks Andrew that fixed it.

**Comment by acairns** [comment]
No problem, glad I could help! :+1:
